/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GenerarOrden;

import EliminarProducto.fachacaEliminarProducto;
import Negocio.dto.ProductoCompradoDto;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pago.Pago;
import subSistemaProductosComprados.FachadaProductosComprados;
import subSistemaProductosComprados.IConsultarProductoCompradoBO;
import subsistema.IGenerarOrden;
import subsistema.ILlenarTabla;
import subsistema.FachadaLLenarTabla;
import subsistema.fachadaGenerarOrden;

/**
 *
 * @author tacot
 */
public class ValidarInfo extends javax.swing.JFrame {

    GenerarOrden FrameOrden;

    ILlenarTabla llenarT = new FachadaLLenarTabla();

    List<ProductoCompradoDto> productosComprados = new ArrayList<>();
    //PC = productosComprados
    IConsultarProductoCompradoBO PC = new FachadaProductosComprados();

    IGenerarOrden orden = new fachadaGenerarOrden();

    /**
     * Creates new form ValidarInfo
     */
    public ValidarInfo() {
        initComponents();

        llenarTabla();
        sacarTotal();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenido = new javax.swing.JPanel();
        botonSiguiente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        agregarP = new javax.swing.JButton();
        EliminarP = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contenido.setBackground(new java.awt.Color(255, 255, 255));
        contenido.setPreferredSize(new java.awt.Dimension(528, 351));

        botonSiguiente.setBackground(new java.awt.Color(24, 50, 77));
        botonSiguiente.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        botonSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        botonSiguiente.setText("Generar Orden");
        botonSiguiente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonSiguiente.setBorderPainted(false);
        botonSiguiente.setFocusPainted(false);
        botonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteActionPerformed(evt);
            }
        });

        tablaProductos.setBackground(new java.awt.Color(214, 217, 223));
        tablaProductos.setForeground(new java.awt.Color(0, 0, 0));
        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Producto", "Proveedor", "P/U", "Cantidad", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProductos.setGridColor(new java.awt.Color(0, 0, 204));
        jScrollPane1.setViewportView(tablaProductos);

        agregarP.setBackground(new java.awt.Color(24, 50, 77));
        agregarP.setForeground(new java.awt.Color(255, 255, 255));
        agregarP.setText("Agregar producto");
        agregarP.setBorderPainted(false);
        agregarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPActionPerformed(evt);
            }
        });

        EliminarP.setBackground(new java.awt.Color(24, 50, 77));
        EliminarP.setForeground(new java.awt.Color(255, 255, 255));
        EliminarP.setText("Eliminar producto ");
        EliminarP.setBorderPainted(false);
        EliminarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarPActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Total:");

        total.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        total.setForeground(new java.awt.Color(0, 0, 0));
        total.setText(" ");

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(contenidoLayout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(contenidoLayout.createSequentialGroup()
                            .addComponent(EliminarP)
                            .addGap(18, 18, 18)
                            .addComponent(botonSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(agregarP))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EliminarP, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSiguiente)
                    .addComponent(agregarP, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguienteActionPerformed

        try {
            orden.realizarOrden(productosComprados);

            fachacaEliminarProducto fep = new fachacaEliminarProducto();

            fep.eliminarTodosLosProductos();
            
            JOptionPane.showMessageDialog(null, "La orden se ha generado correctamente");
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

        FrameOrden.contenido.removeAll();

        Pago pago = new Pago();

        FrameOrden.contenido.add(pago.traerContenido());
       
        FrameOrden.contenido.revalidate();
        FrameOrden.contenido.repaint();

    }//GEN-LAST:event_botonSiguienteActionPerformed

    private void agregarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPActionPerformed
        this.FrameOrden.Contenido.removeAll();

        AgregarProducto agregar = null;
        try {
            agregar = new AgregarProducto(FrameOrden);
        } catch (Exception ex) {
            Logger.getLogger(GenerarOrden.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.FrameOrden.Contenido.add(agregar.traerContenido());

        this.FrameOrden.Contenido.revalidate();
        this.FrameOrden.Contenido.repaint();
    }//GEN-LAST:event_agregarPActionPerformed

    private void EliminarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarPActionPerformed
        if (eliminarPosicion() != -1) {
            fachacaEliminarProducto fep = new fachacaEliminarProducto();

            fep.eliminarProducto(eliminarPosicion());
            llenarTabla();
            sacarTotal();
        } else {
            JOptionPane.showMessageDialog(null, "ninguna fila seleccionada");

        }

    }//GEN-LAST:event_EliminarPActionPerformed

    public javax.swing.JPanel traerContenido() {
        return this.contenido;
    }

    public void posicion(GenerarOrden orden) {
        this.FrameOrden = orden;
    }

    public int eliminarPosicion() {
        int posicion = this.tablaProductos.getSelectedRow();
        return posicion;
    }

    public void llenarTabla() {
        productosComprados = PC.getListaProductosComprados();

        if (productosComprados.isEmpty()) {
            this.botonSiguiente.setVisible(false);
        } else {
            this.botonSiguiente.setVisible(true);
        }

        tablaProductos.removeAll();

        llenarT.llenarTabla(productosComprados, tablaProductos);
    }

    public void sacarTotal() {
        double totalP = 0;
        for (ProductoCompradoDto p : productosComprados) {
            totalP += (p.getCantidad() * p.getPrecio());
        }
        this.total.setText(String.valueOf(totalP));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EliminarP;
    private javax.swing.JButton agregarP;
    private javax.swing.JButton botonSiguiente;
    private javax.swing.JPanel contenido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
